name: Examples
on:
  push:
    paths:
      - "examples/**"

jobs:
  trigger-deploy:
    name: Refresh Examples
    runs-on: ubuntu-latest
    steps:
      - run: curl https://zuplo.com/api/revalidate?tag=api-examples&path=/examples
