name: Deploy
on:
  push:
    branches:
      - main
  workflow_call:


jobs:
  trigger-deploy:
    name: Trigger Deploy
    runs-on: ubuntu-latest
    steps:
    - run: curl ${{secrets.VERCEL_DEPLOY_HOOK}}